### ISSUE TITLE
Petit bug : bug affichage miagie n°2, 4, etc

### ISSUE THREAD

**Issue by Nekoan9119** [Zakarik/foundry-donjonsetchatons#2]
Hello !

Est ce que la feuille de perso est-elle toujours suivie ?

Si oui, voici un petit bug présent depuis le début de celle-ci : 
![Sans titre](https://github.com/Zakarik/foundry-donjonsetchatons/assets/135512175/5023324f-5db8-4ee2-a0e1-139e01811ade)

Toutes les magies pairs manque les métadonnée qualités/succès comme afficher sur le screen. Tester sans module actif également, même soucis !

(Autre petit bug, avec le module ErnieModernUI, les avatars deviennent déformés (beaucoup trop grand) donc a voir si il ne manque pas de limitation de pixel dans le gabarie de l'avatar !)

**Comment by Zakarik** [comment]
Bien sûr que c'est toujours maintenue.
J'ai envoyé une correction pour les deux problèmes mentionnés, plus deux autres problèmes que ton screen a mis en lumière quant aux textes.

Il faut juste me faire les retours... Parce que je n'utilise pas la fiche de manière active actuellement.
