### ISSUE TITLE
Problème de tailles d'image sur les objets (Miagies, équipements)

### ISSUE THREAD

**Issue by Nekoan9119** [Zakarik/foundry-donjonsetchatons#3]
Hello, it's me again ! 😄 

Je me suis rendu compte après coup que le même soucis d'images sans dimension fixe etais présent sur les objets (Miagies et Equipements donc).

Merci pour le correctif rapide sur les deux autres bugs, et désolé de pas avoir vu celui-ci en même temps.

Veuillez acceptez en reconnaissance de ma gratitude cette image de chaton mignon !

Cordialement, Nekoan.

![1440](https://github.com/Zakarik/foundry-donjonsetchatons/assets/135512175/968fbec0-af49-459d-ab20-09d7401b37b9)

**Comment by Zakarik** [comment]
Ca devrait être corrigé !
